import 'package:freezed_annotation/freezed_annotation.dart';

part 'emotion_state.freezed.dart';
part 'emotion_state.g.dart';

/// The recognized emotion types a lobster can express.
enum EmotionType {
  /// Content, at rest, utterly tangping.
  chill,

  /// Happy and energetic.
  happy,

  /// Mildly annoyed or overwhelmed.
  stressed,

  /// Curious about something nearby.
  curious,

  /// Lonely — wants social interaction.
  lonely,

  /// Deeply focused on an activity.
  focused,

  /// Sleepy / low energy.
  sleepy,

  /// Excited — a rare burst of enthusiasm.
  excited,
}

/// Describes the emotional state of a lobster at a point in time.
@freezed
class EmotionState with _$EmotionState {
  const factory EmotionState({
    /// The primary emotion label.
    required EmotionType type,

    /// Intensity of the emotion (0.0–1.0).
    @Default(0.5) double intensity,

    /// Human-readable description, often generated by the AI narrative engine.
    String? description,

    /// The trigger that caused this emotion, e.g. 'weather_change', 'encounter'.
    String? trigger,

    /// ISO-8601 timestamp when this emotion became active.
    required String activatedAt,

    /// ISO-8601 timestamp when this emotion expires (null = indefinite).
    String? expiresAt,
  }) = _EmotionState;

  factory EmotionState.fromJson(Map<String, Object?> json) =>
      _$EmotionStateFromJson(json);
}
