/// The recognized emotion types a lobster can express.
enum EmotionType {
  /// Content, at rest, utterly tangping.
  chill,

  /// Happy and energetic.
  happy,

  /// Mildly annoyed or overwhelmed.
  stressed,

  /// Curious about something nearby.
  curious,

  /// Lonely — wants social interaction.
  lonely,

  /// Deeply focused on an activity.
  focused,

  /// Sleepy / low energy.
  sleepy,

  /// Excited — a rare burst of enthusiasm.
  excited,
}

/// Describes the emotional state of a lobster at a point in time.
class EmotionState {
  const EmotionState({
    required this.type,
    this.intensity = 0.5,
    this.description,
    this.trigger,
    required this.activatedAt,
    this.expiresAt,
  });

  /// The primary emotion label.
  final EmotionType type;

  /// Intensity of the emotion (0.0–1.0).
  final double intensity;

  /// Human-readable description, often generated by the AI narrative engine.
  final String? description;

  /// The trigger that caused this emotion, e.g. 'weather_change', 'encounter'.
  final String? trigger;

  /// ISO-8601 timestamp when this emotion became active.
  final String activatedAt;

  /// ISO-8601 timestamp when this emotion expires (null = indefinite).
  final String? expiresAt;

  EmotionState copyWith({
    EmotionType? type,
    double? intensity,
    String? description,
    String? trigger,
    String? activatedAt,
    String? expiresAt,
  }) {
    return EmotionState(
      type: type ?? this.type,
      intensity: intensity ?? this.intensity,
      description: description ?? this.description,
      trigger: trigger ?? this.trigger,
      activatedAt: activatedAt ?? this.activatedAt,
      expiresAt: expiresAt ?? this.expiresAt,
    );
  }

  factory EmotionState.fromJson(Map<String, Object?> json) {
    return EmotionState(
      type: _emotionTypeFromJson(json['type'] as String?),
      intensity: (json['intensity'] as num?)?.toDouble() ?? 0.5,
      description: json['description'] as String?,
      trigger: json['trigger'] as String?,
      activatedAt: json['activatedAt'] as String? ?? '',
      expiresAt: json['expiresAt'] as String?,
    );
  }

  Map<String, Object?> toJson() {
    return {
      'type': type.name,
      'intensity': intensity,
      if (description != null) 'description': description,
      if (trigger != null) 'trigger': trigger,
      'activatedAt': activatedAt,
      if (expiresAt != null) 'expiresAt': expiresAt,
    };
  }

  @override
  bool operator ==(Object other) {
    return other is EmotionState &&
        other.type == type &&
        other.activatedAt == activatedAt;
  }

  @override
  int get hashCode => Object.hash(type, activatedAt);
}

EmotionType _emotionTypeFromJson(String? value) {
  switch (value) {
    case 'chill':
      return EmotionType.chill;
    case 'happy':
      return EmotionType.happy;
    case 'stressed':
      return EmotionType.stressed;
    case 'curious':
      return EmotionType.curious;
    case 'lonely':
      return EmotionType.lonely;
    case 'focused':
      return EmotionType.focused;
    case 'sleepy':
      return EmotionType.sleepy;
    case 'excited':
      return EmotionType.excited;
    default:
      return EmotionType.chill;
  }
}
