/// The four personality archetypes a lobster can embody.
enum PersonalityArchetype {
  /// 慢活家 — The slow-living homebody.
  slowLiver,

  /// 探险家 — The curious adventurer.
  explorer,

  /// 社交蝶 — The social butterfly.
  socialButterfly,

  /// 独行侠 — The solitary wanderer.
  loner,
}

/// An individual trait dimension of the lobster's personality.
class PersonalityTrait {
  const PersonalityTrait({
    required this.key,
    required this.label,
    required this.value,
    this.plasticity = 0.1,
  });

  /// Trait identifier, e.g. 'openness', 'social_drive', 'adventure'.
  final String key;

  /// Human-readable label.
  final String label;

  /// Current value (0.0–1.0).
  final double value;

  /// How quickly this trait evolves (0.0 = frozen, 1.0 = volatile).
  final double plasticity;

  PersonalityTrait copyWith({
    String? key,
    String? label,
    double? value,
    double? plasticity,
  }) {
    return PersonalityTrait(
      key: key ?? this.key,
      label: label ?? this.label,
      value: value ?? this.value,
      plasticity: plasticity ?? this.plasticity,
    );
  }

  factory PersonalityTrait.fromJson(Map<String, Object?> json) {
    return PersonalityTrait(
      key: json['key'] as String? ?? '',
      label: json['label'] as String? ?? '',
      value: (json['value'] as num?)?.toDouble() ?? 0.0,
      plasticity: (json['plasticity'] as num?)?.toDouble() ?? 0.1,
    );
  }

  Map<String, Object?> toJson() {
    return {
      'key': key,
      'label': label,
      'value': value,
      if (plasticity != 0.1) 'plasticity': plasticity,
    };
  }

  @override
  bool operator ==(Object other) {
    return other is PersonalityTrait &&
        other.key == key &&
        other.value == value;
  }

  @override
  int get hashCode => Object.hash(key, value);
}

/// The full personality DNA of a lobster — a set of trait dimensions
/// plus a dominant archetype.
class PersonalityDna {
  const PersonalityDna({
    required this.archetype,
    required this.traits,
    this.narrative,
    this.lastEvolvedAt,
  });

  /// Dominant personality archetype.
  final PersonalityArchetype archetype;

  /// All trait dimensions.
  final List<PersonalityTrait> traits;

  /// Narrative description generated by the AI engine.
  final String? narrative;

  /// ISO-8601 timestamp of the last evolution event.
  final String? lastEvolvedAt;

  PersonalityDna copyWith({
    PersonalityArchetype? archetype,
    List<PersonalityTrait>? traits,
    String? narrative,
    String? lastEvolvedAt,
  }) {
    return PersonalityDna(
      archetype: archetype ?? this.archetype,
      traits: traits ?? this.traits,
      narrative: narrative ?? this.narrative,
      lastEvolvedAt: lastEvolvedAt ?? this.lastEvolvedAt,
    );
  }

  factory PersonalityDna.fromJson(Map<String, Object?> json) {
    final rawTraits = json['traits'] as List? ?? [];
    return PersonalityDna(
      archetype: _personalityArchetypeFromJson(json['archetype'] as String?),
      traits: rawTraits
          .whereType<Map<dynamic, dynamic>>()
          .map((m) => PersonalityTrait.fromJson(m.cast<String, Object?>()))
          .toList(),
      narrative: json['narrative'] as String?,
      lastEvolvedAt: json['lastEvolvedAt'] as String?,
    );
  }

  Map<String, Object?> toJson() {
    return {
      'archetype': archetype.name,
      'traits': traits.map((t) => t.toJson()).toList(),
      if (narrative != null) 'narrative': narrative,
      if (lastEvolvedAt != null) 'lastEvolvedAt': lastEvolvedAt,
    };
  }

  @override
  bool operator ==(Object other) {
    return other is PersonalityDna && other.archetype == archetype;
  }

  @override
  int get hashCode => archetype.hashCode;
}

PersonalityArchetype _personalityArchetypeFromJson(String? value) {
  switch (value) {
    case 'slowLiver':
      return PersonalityArchetype.slowLiver;
    case 'explorer':
      return PersonalityArchetype.explorer;
    case 'socialButterfly':
      return PersonalityArchetype.socialButterfly;
    case 'loner':
      return PersonalityArchetype.loner;
    default:
      return PersonalityArchetype.slowLiver;
  }
}
