import 'package:freezed_annotation/freezed_annotation.dart';

part 'personality_dna.freezed.dart';
part 'personality_dna.g.dart';

/// The four personality archetypes a lobster can embody.
enum PersonalityArchetype {
  /// 慢活家 — The slow-living homebody.
  slowLiver,

  /// 探险家 — The curious adventurer.
  explorer,

  /// 社交蝶 — The social butterfly.
  socialButterfly,

  /// 独行侠 — The solitary wanderer.
  loner,
}

/// An individual trait dimension of the lobster's personality.
@freezed
class PersonalityTrait with _$PersonalityTrait {
  const factory PersonalityTrait({
    /// Trait identifier, e.g. 'openness', 'social_drive', 'adventure'.
    required String key,

    /// Human-readable label.
    required String label,

    /// Current value (0.0–1.0).
    required double value,

    /// How quickly this trait evolves (0.0 = frozen, 1.0 = volatile).
    @Default(0.1) double plasticity,
  }) = _PersonalityTrait;

  factory PersonalityTrait.fromJson(Map<String, Object?> json) =>
      _$PersonalityTraitFromJson(json);
}

/// The full personality DNA of a lobster — a set of trait dimensions
/// plus a dominant archetype.
@freezed
class PersonalityDna with _$PersonalityDna {
  const factory PersonalityDna({
    /// Dominant personality archetype.
    required PersonalityArchetype archetype,

    /// All trait dimensions.
    required List<PersonalityTrait> traits,

    /// Narrative description generated by the AI engine.
    String? narrative,

    /// ISO-8601 timestamp of the last evolution event.
    String? lastEvolvedAt,
  }) = _PersonalityDna;

  factory PersonalityDna.fromJson(Map<String, Object?> json) =>
      _$PersonalityDnaFromJson(json);
}
